### ISSUE TITLE
Unsupported config option for services: 'influx'

### ISSUE THREAD

**Issue by tpackolus** [k0rventen/apple-health-grafana#1]
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'influx'

**Comment by k0rventen** [comment]
Could you provide the content of the `docker-compose.yml`, as well as the version of docker-compose ?

**Comment by tpackolus** [comment]
docker-compose version 1.23.1, build b02f1306

docker-compose.yml:

services:
  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=health
    volumes:
    - ./provisioning:/etc/grafana/provisioning
  influx:
    image: influxdb:1.8
    environment:
      - INFLUXDB_DB=health
  ingester:
    build: ingester/
    volumes:
    - <local_export.xml_path>:/export.xml

**Comment by k0rventen** [comment]
OK, it seems you are using a very old version of compose (released in Nov 2018 as per [this doc](https://docs.docker.com/compose/release-notes/#1231)), and as I wasn't setting explicitly the compose version (this is now fixed by 0e1565c1e8a5be3f8191e6d9e7efbb64984f4e6f), your version of compose isn't aware that it's incompatible with the v3 compose spec. 

I would suggest upgrading your compose version, or setting manually `version: "2"` at the top of the compose file (which isn't a tested behavior).

Also, don't forget to change the volume path `<local_export.xml_path>` by the real local path of your exported health data file :+1:

**Comment by tpackolus** [comment]
thanks it works I install new version thank you so much
