### ISSUE TITLE
Unable to open export zip: /export.zip is not a zip file

### ISSUE THREAD

**Issue by GeraldPape** [k0rventen/apple-health-grafana#13]
first, thanks for doing a fix for the previous issue and for the cool tool!

So I removed everything and started from scratch again, according to the readme.

I have  a new issue:
```
Attaching to apple-health-grafana-ingester-1
apple-health-grafana-ingester-1  | Unzipping the export file...
apple-health-grafana-ingester-1  | Unable to open export zip: /export.zip is not a zip file
apple-health-grafana-ingester-1 exited with code 1
```

I tried different ways (one at a time) to define the location of the file:
```
    - C:/temp/ap/apple-health-grafana:/export.zip
    - C:\temp\ap\apple-health-grafana:/export.zip
    - C:\\temp\\ap\\apple-health-grafana:/export.zip
```

I can confirm the export.zip is a zip file. I even unzipped and rezipped with 7zip as zip. Same result. But I guess it just can't find the path. So how do I need to specify it on Windows?

Thank you!

**Comment by k0rventen** [comment]
Hi, 

I've just tried on a Windows machine, and it worked by specifying the relative path of the export file as such (I tried with the `test-export2.zip` file from the tests folder):
```
  volumes:
    - ./export.zip:/export.zip 
```

I think your issue is that you are specifying the whole directory to be mapped in the container, rather than the export.zip file ( - C:/temp/ap/apple-health-grafana)

Please test with either the relative path or the absolute export.zip path (which might be C:/temp/ap/apple-health-grafana/export.zip ?) and tell me how it went ! 

Regards :)

**Comment by GeraldPape** [comment]
That worked, thank you!
