### ISSUE TITLE
Support Non Numeric Data

### ISSUE THREAD

**Issue by paulraison** [k0rventen/apple-health-grafana#17]
At present only numeric data is ingested into the InfluxDB, but some metrics, for example AppleStandHour, SleepAnalysis uses a text value. Can these text based value be ingested into InfluxDB as well as the numeric data?

**Comment by k0rventen** [comment]
There is a WIP in the `feat/sleep` [branch](https://github.com/k0rventen/apple-health-grafana/tree/feat/sleep) regarding better sleep related data. 

As for the StandHour data, I'll check if parsing and storing the record's datetime is enough to be able to aggregate in Grafana (daily / weekly average of hours standing up for example)

**Comment by paulraison** [comment]
That's great. Is the code in feat/sleep ready for testing or is it too early yet? This is a great start to the project. Well done.

**Comment by k0rventen** [comment]
Work is under way in #12 to implement more sleep metrics. 

You can already test this branch by using the image tag __:feat-sleep__ in the `docker-compose.yaml`, but things might be broken.

Regarding the AppleStandHour metric, I've pushed f8a171c  to main which sets the value to 1 if standing up during the hour, 0 otherwise. 
I'll try to clean up a bit before releasing a new version with the feature. In the meantime, you can test it with the __:rolling__ tag.

**Comment by paulraison** [comment]
Thanks, I'll test the new AppleStandHour, that'll be very useful.

**Comment by paulraison** [comment]
The AppleStandHour doesn't appear to be working, I only get a value of 0 for all entries regardless of the value in the xml.

**Comment by k0rventen** [comment]
Could you send a few lines of the export.xml containing `AppleStandHour` records ? 

On my side the value is either "HKCategoryValueAppleStandHourStood" or "HKCategoryValueAppleStandHourIdle" and the value in influx is therefore based on that.

**Comment by paulraison** [comment]
Huge apologies! I forgot to add the :rolling tag in the docker-compose file. Now working correctly!
