### ISSUE TITLE
ERROR : missing signature key 

### ISSUE THREAD

**Issue by nbbdoc** [k0rventen/apple-health-grafana#19]
### What happened?

when using 

docker-compose pull

I get the following 

$ docker-compose pull
Pulling ingester (k0rventen/apple-health-grafana-ingester:latest)...
ERROR: missing signature key

Also, may or may not be related..

when using 

docker-compose up ingester

Step 4/5 : COPY *.py .
ERROR: Service 'ingester' failed to build: When using COPY with more than one source file, the destination must be a directory and end with a /

### Environment

OSX 10.13.6

### Relevant log output

```shell
n/a
```

### docker-compose.yml

```shell
using-the-template-data
```

**Comment by k0rventen** [comment]
Hi ! 

Regarding the `ERROR: missing signature key` error, it seems like this is a client issue due to an old version of docker installed (https://github.com/ansible/ansible-runner/issues/1095).
Could you please run `docker version` and paste the output here ?  I believe the latest is 24.x. If it's quite old (older than 20.x) could you try to upgrade docker on your machine ?

The second error you encounter is linked to the first, you shouldn't have to build the image locally as it's already on the dockerhub. Fixing the first will resolve the second.

Regards

**Comment by nbbdoc** [comment]
Thanks for giving it a look !

I did all I could yesterday to update within terminal, and as it turns out the Docker Desktop client was the problem. 

Since docker daemon was removed from command line, before my time using it, using the Mac app starts the daemon in the absence of terminal commands for it on an older OS. ( OS X 10.13.6 - Early-2010 Macbook Pro still going ; ) 

Found and manually installed Docker Desktop app 2.3.5.0 (47376) which was the last 10.13 supported version.

It pulls 19.03.13-beta2 , which works and is newer than the 17.12 I had before. 

Worked immediately. 

Thank you for sharing your code and expertise !
