### ISSUE TITLE
Trying to install on raspberry pi 4 but get an error when using docker-compose pull

### ISSUE THREAD

**Issue by daryn987** [k0rventen/apple-health-grafana#5]
my error is the following, what can i do to alleviate this issue?

Pulling ingester ... pulling from k0rventen/apple-heal...

ERROR: for ingester  no matching manifest for linux/arm/v7 in the manifest list entries
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries

**Comment by k0rventen** [comment]
Hi, this is because the container is only made for x86_64 and arm64 architectures, and you have a 32bit arm version of Raspian installed on your raspberry pi. The Pi 4 actually supports arm64, but that would mean reinstalling it and using the 64bit Raspian. I'll see if I can add support for armv7l when building the container.

**Comment by k0rventen** [comment]
I've added support for armv7 with commit 9cc9eb4, please try to pull the image again !
